name: Linux Image CI

on: [push]

env:
  REGISTRY_URL: docker.pkg.github.com
  REPO_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Login registry
      run: docker login $REGISTRY_URL --username bluekyu -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push linux-base image
      env:
        IMAGE_NAME: linux-base
      run: |
        docker build . --tag $REGISTRY_URL/$REPO_NAME/$IMAGE_NAME:latest
        docker push $REGISTRY_URL/$REPO_NAME/$IMAGE_NAME:latest
      working-directory: ./linux/base  
