name: Linux Images

on: [push]

env:
  REGISTRY_URL: docker.pkg.github.com
  REPO_NAME: ${{ github.repository }}
  GITHUB_SHA: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build linux-base image
      env:
        IMAGE_NAME: linux-base
      run: >-
        docker build
        --tag $IMAGE_NAME:$GITHUB_SHA
        --tag $REGISTRY_URL/$REPO_NAME/$IMAGE_NAME:latest
        .
      working-directory: ./linux/base

    - name: Build linux-android-sdk image
      env:
        IMAGE_NAME: linux-android-sdk
      run: >-
        docker build
        --build-arg IMAGE_REPO=linux-base
        --build-arg IMAGE_TAG=$GITHUB_SHA
        --tag $IMAGE_NAME:$GITHUB_SHA
        --tag $REGISTRY_URL/$REPO_NAME/$IMAGE_NAME:latest
        .
      working-directory: ./linux/android-sdk

    - name: Build linux-android-ndk image
      env:
        IMAGE_NAME: linux-android-ndk
      run: >-
        docker build
        --build-arg IMAGE_REPO=linux-android-sdk
        --build-arg IMAGE_TAG=$GITHUB_SHA
        --tag $IMAGE_NAME:$GITHUB_SHA
        --tag $REGISTRY_URL/$REPO_NAME/$IMAGE_NAME:latest
        .
      working-directory: ./linux/android-ndk

    - name: Push Images
      evn:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "$GITHUB_TOKEN" | docker login $REGISTRY_URL --username bluekyu --password-stdin
        docker push $REGISTRY_URL/$REPO_NAME/linux-base:latest
        docker push $REGISTRY_URL/$REPO_NAME/linux-android-sdk:latest
        docker push $REGISTRY_URL/$REPO_NAME/linux-android-ndk:latest

