name: Windows Images

on: [push]

env:
  REGISTRY_URL: docker.pkg.github.com
  REPO_NAME: ${{ github.repository }}
  GITHUB_SHA: ${{ github.sha }}

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build windows-msvc16 image
      env:
        IMAGE_NAME: windows-msvc16
      run: >-
        docker build
        --tag "${env:IMAGE_NAME}:${env:GITHUB_SHA}"
        --tag "${env:REGISTRY_URL}/${env:REPO_NAME}/${env:IMAGE_NAME}:latest"
        .
      working-directory: ./windows/msvc16

    - name: Push Images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ${env:GITHUB_TOKEN} | docker login "${env:REGISTRY_URL}" --username bluekyu --password-stdin
        docker push "${env:REGISTRY_URL}/${env:REPO_NAME}/windows-msvc16:latest"
